spring.application.name=Springboot-Demo

logging.level.org.springframework=debug

spring.profiles.active=dev

currency-service.url=hhtp://default.com/
currency-service.username=bhaskar
currency-service.key	=bhaskarkey
