spring.application.name=Springboot-Demo

logging.level.org.springframework=info

currency-service.url=hhtp://defaultprod.com/
currency-service.username=bhaskarprod
currency-service.key	=bhaskarprodkey
